### ISSUE TITLE
Invalid account credentials crashes homebridge

### ISSUE THREAD

**Issue by tbaur** [node-alarm-dot-com/homebridge-node-alarm-dot-com#116]
**Describe the bug**
Alarm.com threw an error and the plugin crashed Homebridge entirely. Requires better error handling.

**To Reproduce**
[9/18/2023, 9:18:48 AM] Error: GET https://www.alarm.com/web/api/identities failed: GET https://www.alarm.com/web/api/identities failed: [object Object]
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:150:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getIdentitiesState (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:134:12)
    at ADCPlatform.getAccountSettings (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:378:24)
    at ADCPlatform.refreshDevices (/usr/local/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:392:5)
[9/18/2023, 9:18:48 AM] Got SIGTERM, shutting down Homebridge...

**Comment by chase9** [comment]
Hi Tim,

Agreed, but what do you think the plugin should do when we encounter fatal errors? Do you think a red line warning in the log is enough?

Also, I'm guessing the error here is that login failed due to missing MFA but could you please confirm?

**Comment by chase9** [comment]
Just pushed up some code to the beta branch which will stop homebridge crashing the getAccountSettings() method fails.

**Comment by chase9** [comment]
Fixed in b7736ea

**Comment by chase9** [comment]
Resolved in stable v1.10.1
