### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by chase9** [node-alarm-dot-com/homebridge-node-alarm-dot-com#48]
I think the project could benefit from a conversion to Typescript for the same reasons as mentioned in mkormendy/node-alarm-dot-com#10. This issue is our blocker before moving forward.

**Comment by chase9** [comment]
Blocked by mkormendy/node-alarm-dot-com#11

**Comment by chase9** [comment]
I've pushed to the typescript branch. If anyone would be willing to test that would be great!

**Comment by iBanks3** [comment]
> I've pushed to the typescript branch. If anyone would be willing to test that would be great!

I don’t mind testing out things for ya but I’m new to this whole raspberry pi Homebridge setup. Willing to help where I can.

**Comment by chase9** [comment]
Thanks for the offer, @iBanks3. I'm not sure how to bundle this in a convenient way for you yet, but in the meantime you should be able to copy the source to your global node_modules folder the override the old files.

If you'd like, there is a discord channel where we can talk about this in realtime: https://discord.gg/w3KkTeht

**Comment by iBanks3** [comment]
After overwriting the files I am getting the following. 2FA is not enabled. 

[11/25/2020, 3:05:56 PM] [Security System] Error: No afg cookie: ASP.NET_SessionId=cvzmnxwylisngjqz4lqlrdaq; cookieTest=1; twoFactorAuthenticationId=0CE029CB40B337607E0697AA2C920E13F19272B7204D20E18E38069CEA38B179; IsFromNewSite=1; fromASP=; IsFromSeamlessLogin=; login=; ST=; SeamlessLoginEnabled=; loggedInAsSubscriber=1; twoFactorAuthenticationSkipped-8505422=false; BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTPS=!Zzr/OnNVki3vQaHNzUFX+zqT5KjmGPR764em/20VSYBqncSpDMi7Wrut5mH2lYaWGkD18TOTZks18g8=
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:149:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
