### ISSUE TITLE
Receiving "Doors" as "Lights"

### ISSUE THREAD

**Issue by mbmarlowe** [node-alarm-dot-com/homebridge-node-alarm-dot-com#52]
**Describe the bug**
I am receiving door locks as lights.  I have uninstalled removed cache, etc. but because of this further updates do not work.  I am also having an issue with garage doors but I dont understand the issue.

**To Reproduce**
Add plugin and login, on start-up it sees devices incorrectly.

**Expected behavior**

To see devices correctly

**Screenshots**

**ADC-SystemStates.json**

**Homebridge System (please complete the following information):**
* **Node.js Version**: v14.15.1
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.1.6
* **Operating System**: Raspbian 
* **Process Supervisor**:  hb-service / 

**Additional context**

[25/11/2020, 17:13:23] [Security System] Received 1 partitions from Alarm.com
[25/11/2020, 17:13:23] [Security System] Adding partition SYSTEM (id=95222472-127, uuid=8d24d40e-e50c-434e-93bd-57f802a47fc2)
[25/11/2020, 17:13:23] [Security System] Updating partition SYSTEM (95222472-127), state=3, prev=null
[25/11/2020, 17:13:23] [Security System] Updating partition SYSTEM (95222472-127), desiredState=3, prev=null
[25/11/2020, 17:13:23] [Security System] Updating partition SYSTEM (95222472-127), statusFault=false, prev=null
[25/11/2020, 17:13:23] [Security System] Added partition SYSTEM (95222472-127)
[25/11/2020, 17:13:23] [Security System] Received 42 sensors from Alarm.com
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Back Door" (id=95222472-27, uuid=9e4426fc-4205-463e-9a2b-446bcc8def44)
[25/11/2020, 17:13:23] [Security System] Updating sensor Back Door (95222472-27), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Back Door (95222472-27)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Basement Left Window" (id=95222472-19, uuid=746cf0c7-8868-402a-980d-4ebaea9e9991)
[25/11/2020, 17:13:23] [Security System] Updating sensor Basement Left Window (95222472-19), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Basement Left Window (95222472-19)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Basement Right Window" (id=95222472-18, uuid=85a0cbf5-99ae-454f-b096-b00205c23d37)
[25/11/2020, 17:13:23] [Security System] Updating sensor Basement Right Window (95222472-18), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Basement Right Window (95222472-18)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Dining Left Window" (id=95222472-8, uuid=9c79252a-006d-4747-886a-810d811e712c)
[25/11/2020, 17:13:23] [Security System] Updating sensor Dining Left Window (95222472-8), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Dining Left Window (95222472-8)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Dining Right Window" (id=95222472-10, uuid=f1ab82c1-e880-4b30-926d-d4ff6868bc96)
[25/11/2020, 17:13:23] [Security System] Updating sensor Dining Right Window (95222472-10), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Dining Right Window (95222472-10)
[25/11/2020, 17:13:23] [Security System] Adding Occupancy Sensor "Dining Room Motion Detector" (id=95222472-26, uuid=f733ac92-337d-45fa-9c30-308f12957072)
[25/11/2020, 17:13:23] [Security System] Updating sensor Dining Room Motion Detector (95222472-26), state=1, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Dining Room Motion Detector (95222472-26)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Downstairs Bathroom Window" (id=95222472-20, uuid=34d8eb2c-82b0-42c6-a5a4-411bfab7c9e6)
[25/11/2020, 17:13:23] [Security System] Updating sensor Downstairs Bathroom Window (95222472-20), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Downstairs Bathroom Window (95222472-20)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Downstairs CO Detector" (id=95222472-2, uuid=2f85cdba-ab65-4606-9478-b18746721a94)
[25/11/2020, 17:13:23] [Security System] Updating sensor Downstairs CO Detector (95222472-2), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Downstairs CO Detector (95222472-2)
[25/11/2020, 17:13:23] [Security System] Adding Occupancy Sensor "Downstairs Facing Door Motion Detector" (id=95222472-37, uuid=5d8a0e99-85f1-4a66-874f-2903da3ddf7b)
[25/11/2020, 17:13:23] [Security System] Updating sensor Downstairs Facing Door Motion Detector (95222472-37), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Downstairs Facing Door Motion Detector (95222472-37)
[25/11/2020, 17:13:23] [Security System] Adding Occupancy Sensor "Downstairs Motion Detector" (id=95222472-23, uuid=6fd481e6-1133-4e82-9182-b4276bc7995b)
[25/11/2020, 17:13:23] [Security System] Updating sensor Downstairs Motion Detector (95222472-23), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Downstairs Motion Detector (95222472-23)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Downstairs Smoke Detector" (id=95222472-31, uuid=feeabe2d-f04d-4e9a-873a-19ea70c76d09)
[25/11/2020, 17:13:23] [Security System] Updating sensor Downstairs Smoke Detector (95222472-31), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Downstairs Smoke Detector (95222472-31)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Front Door" (id=95222472-29, uuid=df7b5b4b-0688-4d20-be35-6d8899c8ef1a)
[25/11/2020, 17:13:23] [Security System] Updating sensor Front Door (95222472-29), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Front Door (95222472-29)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Garage Door" (id=95222472-28, uuid=4ecdc005-a979-4c98-a41e-1d82b93105d7)
[25/11/2020, 17:13:23] [Security System] Updating sensor Garage Door (95222472-28), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Garage Door (95222472-28)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Garage Front Window" (id=95222472-34, uuid=b2741b9d-6e48-4498-8979-c79917635161)
[25/11/2020, 17:13:23] [Security System] Updating sensor Garage Front Window (95222472-34), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Garage Front Window (95222472-34)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Garage Side Window" (id=95222472-35, uuid=c17de9ab-61a9-4184-a5fb-88b8de840503)
[25/11/2020, 17:13:23] [Security System] Updating sensor Garage Side Window (95222472-35), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Garage Side Window (95222472-35)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Glass Break" (id=95222472-21, uuid=2ebd13c0-2a7c-4959-be0a-65b8691b3c47)
[25/11/2020, 17:13:23] [Security System] Updating sensor Glass Break (95222472-21), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Glass Break (95222472-21)
[25/11/2020, 17:13:23] [Security System] Adding Occupancy Sensor "Hallway Motion Detector" (id=95222472-24, uuid=f5050563-582a-4839-b952-308374db813f)
[25/11/2020, 17:13:23] [Security System] Updating sensor Hallway Motion Detector (95222472-24), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Hallway Motion Detector (95222472-24)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "iPhone-..D84" (id=95222472-5296, uuid=76768c66-ca6e-4765-8bdb-e34b36e4ce80)
[25/11/2020, 17:13:23] [Security System] Updating sensor iPhone-..D84 (95222472-5296), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor iPhone-..D84 (95222472-5296)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Iron Room Window" (id=95222472-12, uuid=37c4c208-cd9b-4cc0-b7f9-8b494fb734b5)
[25/11/2020, 17:13:23] [Security System] Updating sensor Iron Room Window (95222472-12), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Iron Room Window (95222472-12)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Jenny’s iPhone" (id=95222472-5297, uuid=e81e95e5-48de-447a-8d37-e4bbdec2a29d)
[25/11/2020, 17:13:23] [Security System] Updating sensor Jenny’s iPhone (95222472-5297), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Jenny’s iPhone (95222472-5297)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Kitchen Left Window" (id=95222472-5, uuid=ee517174-2955-4f25-b574-9cd4bed4eae2)
[25/11/2020, 17:13:23] [Security System] Updating sensor Kitchen Left Window (95222472-5), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Kitchen Left Window (95222472-5)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Kitchen Right Window" (id=95222472-4, uuid=054ab723-2710-4e3f-a536-64af3e7e1bbc)
[25/11/2020, 17:13:23] [Security System] Updating sensor Kitchen Right Window (95222472-4), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Kitchen Right Window (95222472-4)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Living Room Left Window" (id=95222472-11, uuid=19b77ecd-6f13-4621-a439-ef0092b032eb)
[25/11/2020, 17:13:23] [Security System] Updating sensor Living Room Left Window (95222472-11), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Living Room Left Window (95222472-11)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Living Room Right Window" (id=95222472-13, uuid=5e52422e-84ed-4dcf-a163-6766c5ab3d33)
[25/11/2020, 17:13:23] [Security System] Updating sensor Living Room Right Window (95222472-13), state=0, prev=null
[25/11/2020, 17:13:23] [Security System] Added sensor Living Room Right Window (95222472-13)
[25/11/2020, 17:13:23] [Security System] Adding Contact Sensor "Mackenzie Front Window" (id=95222472-15, uuid=4cacd532-04a8-4f22-9abc-66f27e44b1dd)
[25/11/2020, 17:13:24] [Security System] Updating sensor Mackenzie Front Window (95222472-15), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Mackenzie Front Window (95222472-15)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Mackenzie Side Window" (id=95222472-17, uuid=45490115-0478-4a0e-85eb-6631cfdb72c8)
[25/11/2020, 17:13:24] [Security System] Updating sensor Mackenzie Side Window (95222472-17), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Mackenzie Side Window (95222472-17)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Mackenzie’s iPhone" (id=95222472-5298, uuid=a71d47ba-048d-4d97-98ff-40f4c3307d76)
[25/11/2020, 17:13:24] [Security System] Updating sensor Mackenzie’s iPhone (95222472-5298), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Mackenzie’s iPhone (95222472-5298)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Master Rear Window" (id=95222472-6, uuid=b6f28a9a-1582-4178-ad8b-49d3fafffe48)
[25/11/2020, 17:13:24] [Security System] Updating sensor Master Rear Window (95222472-6), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Master Rear Window (95222472-6)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Master Side Window" (id=95222472-14, uuid=6c896747-9312-4f65-a68c-29b5c385d214)
[25/11/2020, 17:13:24] [Security System] Updating sensor Master Side Window (95222472-14), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Master Side Window (95222472-14)
[25/11/2020, 17:13:24] [Security System] Adding Occupancy Sensor "New Motion 5" (id=95222472-38, uuid=9b2c1e50-c2c5-4941-a8ee-1a1d84eaa9d0)
[25/11/2020, 17:13:24] [Security System] Updating sensor New Motion 5 (95222472-38), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor New Motion 5 (95222472-38)
[25/11/2020, 17:13:24] [Security System] Adding Occupancy Sensor "Office Motion Detector" (id=95222472-39, uuid=24eacc49-1a81-4ef3-969a-4da987d2e3d7)
[25/11/2020, 17:13:24] [Security System] Updating sensor Office Motion Detector (95222472-39), state=1, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Office Motion Detector (95222472-39)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Panel Camera" (id=95222472-229, uuid=20ce65de-7cd2-4a70-b035-f327d384c90c)
[25/11/2020, 17:13:24] [Security System] Updating sensor Panel Camera (95222472-229), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Panel Camera (95222472-229)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Panel Glass Break" (id=95222472-33, uuid=82b9f1e3-57eb-4925-90aa-85669e60d25a)
[25/11/2020, 17:13:24] [Security System] Updating sensor Panel Glass Break (95222472-33), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Panel Glass Break (95222472-33)
[25/11/2020, 17:13:24] [Security System] Adding Occupancy Sensor "Panel Motion" (id=95222472-36, uuid=6f38f13e-3b91-496f-b1a7-e7372e7c4711)
[25/11/2020, 17:13:24] [Security System] Updating sensor Panel Motion (95222472-36), state=1, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Panel Motion (95222472-36)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Safe" (id=95222472-16, uuid=c41966fc-b9a6-4cf9-b787-09f1c6b2890b)
[25/11/2020, 17:13:24] [Security System] Updating sensor Safe (95222472-16), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Safe (95222472-16)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Sliding Door" (id=95222472-9, uuid=63b9ab18-41cc-423f-ae91-1cfecee3a32a)
[25/11/2020, 17:13:24] [Security System] Updating sensor Sliding Door (95222472-9), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Sliding Door (95222472-9)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Upstairs Bathroom Window" (id=95222472-7, uuid=966d5ac4-d89e-4fce-a655-ae6eb8bd90e4)
[25/11/2020, 17:13:24] [Security System] Updating sensor Upstairs Bathroom Window (95222472-7), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Upstairs Bathroom Window (95222472-7)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Upstairs CO Detector" (id=95222472-1, uuid=ddce3f27-8722-40d7-9ab3-b7939f8c6fca)
[25/11/2020, 17:13:24] [Security System] Updating sensor Upstairs CO Detector (95222472-1), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Upstairs CO Detector (95222472-1)
[25/11/2020, 17:13:24] [Security System] Adding Occupancy Sensor "Upstairs Motion Detector" (id=95222472-25, uuid=245643c6-370f-4fff-a46a-25f019344d1d)
[25/11/2020, 17:13:24] [Security System] Updating sensor Upstairs Motion Detector (95222472-25), state=1, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Upstairs Motion Detector (95222472-25)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Upstairs Smoke Detector" (id=95222472-30, uuid=81ab208a-2da2-4faa-be83-5c610ab9b1f1)
[25/11/2020, 17:13:24] [Security System] Updating sensor Upstairs Smoke Detector (95222472-30), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Upstairs Smoke Detector (95222472-30)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Utility Flood Sensor" (id=95222472-22, uuid=21498a91-2953-4261-bb08-1d02fa8e5b4b)
[25/11/2020, 17:13:24] [Security System] Updating sensor Utility Flood Sensor (95222472-22), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Utility Flood Sensor (95222472-22)
[25/11/2020, 17:13:24] [Security System] Adding Contact Sensor "Window 1" (id=95222472-3, uuid=321d91aa-6d67-41ca-b512-71b38661688f)
[25/11/2020, 17:13:24] [Security System] Updating sensor Window 1 (95222472-3), state=0, prev=null
[25/11/2020, 17:13:24] [Security System] Added sensor Window 1 (95222472-3)

BEGIN ISSUE...

[25/11/2020, 17:13:24] [Security System] Received 3 lights from Alarm.com

I have no lights!

[25/11/2020, 17:13:24] [Security System] Adding Door Lock "Front Door" (id=95222472-1235, uuid=411e70c7-ebdc-4913-8e64-c7f4c483dcee) (1 1)
[25/11/2020, 17:13:24] [Security System] Added lock Front Door (95222472-1235)
[25/11/2020, 17:13:24] [Security System] Adding Door Lock "Back Door" (id=95222472-1236, uuid=51642898-c628-4741-b5e6-66b47784ec07) (1 1)
[25/11/2020, 17:13:25] [Security System] Added lock Back Door (95222472-1236)
[25/11/2020, 17:13:25] [Security System] Adding Door Lock "Garage Door" (id=95222472-1243, uuid=a60d1be3-5ddc-4a43-821f-83b70896b8db) (1 1)
[25/11/2020, 17:13:25] [Security System] Added lock Garage Door (95222472-1243)
[25/11/2020, 17:13:25] [Security System] Received 1 locks from Alarm.com
[25/11/2020, 17:13:25] [Security System] Adding Garage Door "Garage Door" (id=95222472-2201, uuid=5fad585c-788c-4179-8fed-df6ae2fe8db1) (2 2)
[25/11/2020, 17:13:25] [Security System] Updating garage Garage Door (95222472-2201), state=1, prev=2
[25/11/2020, 17:13:25] [Security System] Added garage-door Garage Door (95222472-2201)

It sees and adds the garage door, then says there is no garage doors:

[25/11/2020, 17:13:25] [Security System] Received no garages from Alarm.com. If you are expecting
              garages in your Alarm.com setup, you may need to check that your
              provider has assigned garages in your Alarm.com account

I don't have a front door light, I have a front door door.

[25/11/2020, 17:14:23] [Security System] Updating light Front Door (95222472-1235), state=undefined, prev=1
[25/11/2020, 17:14:23] [Security System] TypeError: Cannot read property 'getCharacteristic' of undefined
    at ADCPlatform.statLightState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:793:9)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:299:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:294:27
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:265:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[25/11/2020, 17:14:23] [Security System] /var/lib/homebridge/ADC-SystemStates.json written
[25/11/2020, 17:15:30] [Security System] Updating light Back Door (95222472-1236), state=undefined, prev=1
[25/11/2020, 17:15:30] [Security System] TypeError: Cannot read property 'getCharacteristic' of undefined
    at ADCPlatform.statLightState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:793:9)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:299:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:294:27
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:265:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[25/11/2020, 17:15:30] [Security System] /var/lib/homebridge/ADC-SystemStates.json written

**Comment by mbmarlowe** [comment]
Looking through the log, it looks like it sees the locks as lights and the garage door as locks.  Received 3 lights and 1 lock, it's 3 locks and 1 garage door.  I believe what ever is causing the issue about the locks is causing the issue with the garage door.

**Comment by ngori** [comment]
Your issues is similar to #50 and #47.  Different alarm.com providers appear to be passing devices in different orders. The current fixed order works for many but not everyone clearly.   I believe Chase already has this in his queue to work on handling different orders dynamically.

**Comment by mbmarlowe** [comment]
I see that now, and based on that I made this change and it is now working as expected; So it is the order:

In `/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js`:

`231c231`
`<         const [partitions, sensors, lights, locks, garageDoors] = resultingSystemComponents`
`---`
`>         const [partitions, sensors, locks, garageDoors, lights] = resultingSystemComponents`
`237d236`
`<           lights: typeof lights != 'undefined' ? lights.data : [],`
`239a239`
`>           lights: typeof lights != 'undefined' ? lights.data : [],`

**Comment by iBanks3** [comment]
Not sure if this will be helpful to anyone but I came across something that kinda works for me. I have ADT using alarm.com service and app. With Homebridge and this plugin I have only been able to turn off a light when on but unable to turn on the light. So I tried the rearrangement of the order in which the accessories are setup in the index.js file as follows:

partitions, sensors, locks, garageDoors, lights. Then I tried partitions, sensors, garageDoors, locks, lights. Neither allowed me to control lights other than turning off. So I scrolled around the document and noticed 

const Light_States = {
  ON: 2,
  OFF: 3

So I changed that to ON: 1 and OFF: 2 and now I am able to turn the lights on and off. So I wanted to test this setup out with the original index.js without rearranging the order of the accessories but just modifying the number next to the on/off state and I am achieving the same result. 

The only issue I am now running into is that with both the modified index.js that has the change in order and original index.js and both have the 1,2 status the light will turn on but 35 seconds later the Home app state will toggle to off though the light is still on and the error displayed in the log is:

[11/25/2020, 7:18:05 PM] [Security System] Changing light (97265971-1210, false light level true)
[11/25/2020, 7:18:08 PM] [Security System] Changing light (97265971-1210, true light level false)
[11/25/2020, 7:18:09 PM] [Security System] Updating light Master Bedroom Light (97265971-1210), state=undefined, prev=true
[11/25/2020, 7:18:20 PM] [Security System] Changing light (97265971-1210, true light level undefined)
[11/25/2020, 7:18:56 PM] [Security System] Updating light Master Bedroom Light (97265971-1210), state=0, prev=true
[11/25/2020, 7:19:03 PM] [Security System] Changing light (97265971-1210, true light level 0)
[11/25/2020, 7:19:15 PM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/97265971-1210/turnOn failed: request to https://www.alarm.com/web/api/devices/lights/97265971-1210/turnOn failed, reason: read ECONNRESET
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:573:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4327) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:842:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[11/25/2020, 7:19:26 PM] [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/7303791 failed: request to https://www.alarm.com/web/api/systems/systems/7303791 failed, reason: read ECONNRESET
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:544:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
[11/25/2020, 7:19:29 PM] [Security System] Updating light Master Bedroom Light (97265971-1210), state=undefined, prev=true
[11/25/2020, 7:19:35 PM] [Security System] Changing light (97265971-1210, true light level undefined)
[11/25/2020, 7:19:56 PM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/97265971-1210/turnOn failed: request to https://www.alarm.com/web/api/devices/lights/97265971-1210/turnOn failed, reason: read ECONNRESET
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:573:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4327) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/index.js:842:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[11/25/2020, 7:20:05 PM] [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/7303791 failed: request to https://www.alarm.com/web/api/systems/systems/7303791 failed, reason: read ECONNRESET
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:544:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
[11/25/2020, 7:20:07 PM] [Security System] Error: GET https://www.alarm.com/web/api/systems/systems/7303791 failed: request to https://www.alarm.com/web/api/systems/systems/7303791 failed, reason: read ECONNRESET
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:544:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
[11/25/2020, 7:20:58 PM] [Security System] Updating light Master Bedroom Light (97265971-1210), state=0, prev=true

Yet if I tap twice on the light icon in the Home app, it will then turn the light off and I can turn it back on and the above will happen again. Again, unsure if this helps with anything but just wanted to report my findings.

**Comment by chase9** [comment]
Are you able to check the responses for turning lights on and off through the alarm.com website? Those states were taken from my lights through the website, but maybe they're different when you don't have dimmers? It was odd that there was no 0 or 1 state.

I can help you if you're not sure what I'm talking about.

**Comment by iBanks3** [comment]
I can definitely check it out for you right now, just let me know how. I had tried with a 0,1 state and it did nothing at all so I figured because for other values, 0 = unknown is the reason why a value of 0,1 didn’t work 1,2 works just runs into state change issue mentioned above. I do have one dimmer module in my home that was installed and is connected with the alarm.com system but it is not in use.

**Comment by papaavi** [comment]
> I see that now, and based on that I made this change and it is now working as expected; So it is the order:
> 
> In `/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js`:
> 
> `231c231`
> `< const [partitions, sensors, lights, locks, garageDoors] = resultingSystemComponents`
> `---`
> `> const [partitions, sensors, locks, garageDoors, lights] = resultingSystemComponents`
> `237d236`
> `< lights: typeof lights != 'undefined' ? lights.data : [],`
> `239a239`
> `> lights: typeof lights != 'undefined' ? lights.data : [],`

This worked for my situation, completely resolved my issue.

**Comment by cjones813** [comment]
> In `/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js`:
> 
> `231c231`
> `< const [partitions, sensors, lights, locks, garageDoors] = resultingSystemComponents`
> `---`
> `> const [partitions, sensors, locks, garageDoors, lights] = resultingSystemComponents`
> `237d236`
> `< lights: typeof lights != 'undefined' ? lights.data : [],`
> `239a239`
> `> lights: typeof lights != 'undefined' ? lights.data : [],`

This worked for me too. My service is provided directly by alarm.com

**Comment by JCallender73** [comment]
Can someone give me description or instructions on how to make these changes?

**Comment by chase9** [comment]
I just pushed v1.7.2-beta.7 which includes a more consistent parsing of devices. Could you test and see if this fixes your issue?

**Comment by JCallender73** [comment]
I don't see a Beta 7 listed, newest Beta version I see is Beta 4 which is what I am running.

![image](https://user-images.githubusercontent.com/82294589/118418244-b1832680-b685-11eb-8088-5c9bf8fd7da8.png)

**Comment by chase9** [comment]
I’m unfamiliar with HOOBs, but it looks like you’re pointed at my personal profile on GitHub? Make sure you’re pointed at this package: https://www.npmjs.com/package/homebridge-node-alarm-dot-com <https://www.npmjs.com/package/homebridge-node-alarm-dot-com>

Chase Lau

**Comment by JCallender73** [comment]
I tried to install it through terminal but got these errors.

![image](https://user-images.githubusercontent.com/82294589/118421167-8ea94000-b68e-11eb-8dcf-4e95e558088d.png)

**Comment by chase9** [comment]
The package name should be homebridge-node-alarm-dot-com, not homebridge-node-alarm-com. Add the -dot- in there and let me know if it works.

**Comment by JCallender73** [comment]
I was able to get Beta 7 loaded but now I am getting the following error and all of my accessories are now missing.

5/16/2021, 10:14:29 PMNode Alarm Dot Com BridgeSecurity SystemERRORTypeError: Cannot read property 'data' of undefined.

![image](https://user-images.githubusercontent.com/82294589/118424031-5b69af80-b694-11eb-9379-3fe8a05995e1.png)

**Comment by chase9** [comment]
Do you get a stack trace with that error? Perhaps HOOBs didn’t run an `npm install` To get dependencies?

Chase Lau

Please excuse any grammatical errors as this was sent from my iPhone.

**Comment by JCallender73** [comment]
Below is the entire log after the login attempt:

5/17/2021, 7:28:04 AMNode Alarm Dot Com BridgeSecurity SystemERRORError: GET https://www.alarm.com/web/api/systems/systems/10895699 failed: request to https://www.alarm.com/web/api/systems/systems/10895699 failed, reason: read ECONNRESET
5/17/2021, 7:29:13 AMNode Alarm Dot Com BridgeSecurity SystemERRORTypeError: Cannot read property 'data' of undefined
5/17/2021, 7:34:53 AMNode Alarm Dot Com BridgeSecurity SystemERRORError: GET https://www.alarm.com/web/api/systems/systems/10895699 failed: [object Object]
5/17/2021, 7:36:33 AMNode Alarm Dot Com BridgeSecurity SystemERRORError: GET https://www.alarm.com/web/api/systems/systems/10895699 failed: [object Object]

**Comment by JCallender73** [comment]
I have now did a full factory reset and reinstalled the plugin and still have the errors.  I am currently running 4.0.60 Beta version of HOOBS, could this be causing the issue?

**Comment by JCallender73** [comment]
With Beta 9 I have gotten my accessories back now and the garage open works.  Still getting errors but things are working.
