### ISSUE TITLE
Lock accessory status issue

### ISSUE THREAD

**Issue by rwbisme** [node-alarm-dot-com/homebridge-node-alarm-dot-com#59]
After instaling latest 1.7.1 I get the following error:
Error: Trouble getting HomeKit accessory information for 100302700-2201
    at ADCPlatform.statLockState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:976:13)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:340:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:335:26
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

All other accessories are working fine.  the garage door issue seems to be resolved and this is a great fix other than this one issue.  I have a Kwikset lock and it works fine on Alarm.com app and site.

**Comment by rwbisme** [comment]
i exercised the lock through homekit and it unocked.  I then locked it via homekit and then got the error

[2/8/2021, 8:34:32 AM] [Security System] TypeError: Cannot read property 'updateCharacteristic' of undefined
    at ADCPlatform.statLightState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/dist/index.js:625:17)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:328:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:323:27
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

At the next read the initial error comes back again.

**Comment by chase9** [comment]
I believe this to be an issue with how I've setup the plugin to pull its dependencies. I'm sorry, and I'll make changed to avoid this in the future.

In the meantime, completely removing the plugin and then reinstalling it is likely your best bet. If you tell me whether you're using the Homebridge UI or the CLI I can give you instructions.

**Comment by rwbisme** [comment]
> I believe this to be an issue with how I've setup the plugin to pull its dependencies. I'm sorry, and I'll make changed to avoid this in the future.
> 
> In the meantime, completely removing the plugin and then reinstalling it is likely your best bet. If you tell me whether you're using the Homebridge UI or the CLI I can give you instructions.

I am using the Homebridge UI on a RPi.  Thanks.

**Comment by chase9** [comment]
Go to plugins, click the wrench on the card for homebridge-node-alarm-dot-com, click uninstall. Don't remove your config or you'll need to set it all up again! Here's a screenshot from mine:

<img width="671" alt="Screen Shot 2021-02-12 at 8 10 34 AM" src="https://user-images.githubusercontent.com/6013163/107778696-00799280-6d0a-11eb-8dee-d5ff5ca92153.png">

After that you can reinstall the plugin and the right dependency should be pulled in.

**Comment by rwbisme** [comment]
I uninstalled and reinstalled as above.  Now getting the following:

[2/12/2021, 7:40:44 PM] [Security System] Updating light Lock (ID:2) (100302700-1200), state=-1, prev=1
[2/12/2021, 7:40:44 PM] [Security System] TypeError: Cannot read property 'updateCharacteristic' of undefined
    at ADCPlatform.statLightState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/dist/index.js:625:17)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:328:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:323:27
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/12/2021, 7:41:44 PM] [Security System] Error: Trouble getting HomeKit accessory information for 100302700-2201
    at ADCPlatform.statLockState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:976:13)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:340:20
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:335:26
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by rwbisme** [comment]
It’s strange, still getting this error.

 [Security System] Error: Trouble getting HomeKit accessory information for 100302700-2201
at ADCPlatform.statLockState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:976:13)
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:340:20
at Array.forEach ()
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:335:26
at Array.forEach ()
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
at processTicksAndRejections (internal/process/task_queues.js:93:5)

but the lock works and I can unlock it and lock it in HomeKit but after a few minutes the error shows up again.

**Comment by rwbisme** [comment]
> Go to plugins, click the wrench on the card for homebridge-node-alarm-dot-com, click uninstall. Don't remove your config or you'll need to set it all up again! Here's a screenshot from mine:
> 
> <img alt="Screen Shot 2021-02-12 at 8 10 34 AM" width="671" src="https://user-images.githubusercontent.com/6013163/107778696-00799280-6d0a-11eb-8dee-d5ff5ca92153.png">
> 
> After that you can reinstall the plugin and the right dependency should be pulled in.

**_after reset and update to 1.7.1 I get the following_**

[Security System] Error: Trouble getting HomeKit accessory information for 100302700-2201
at ADCPlatform.statLockState (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:976:13)
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:340:20
at Array.forEach ()
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:335:26
at Array.forEach ()
at /usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:295:22
at processTicksAndRejections (internal/process/task_queues.js:93:5)

**_and then a few minutes later_**

[3/12/2021, 2:00:56 PM] [homebridge-node-alarm-dot-com] Error: 
    at LockCurrentState.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at LockCurrentState.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2114:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1517:24
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at LockCurrentState.<anonymous> (/usr/lib/node_modules/homebridge-node-alarm-dot-com/src/index.ts:952:9)
    at LockCurrentState.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1493:14
    at new Promise (<anonymous>)
    at LockCurrentState.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1491:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)

**Comment by Soorma07** [comment]
I ran into a similar issue with my ZWave lock. I added a ZWave light switch plug module in between my panel and the lock to act as a repeater boosting the ZWave signal. This helped increase the reliability.

**Comment by christopherlaing** [comment]
First off, thank you for your hard work on this module!  I am experiencing a challenge and I wanted to give you some backstory on it.  It is in regards to the ZWave lock that is tied to my alarm system.   For about a day it was working flawlessly.  The next day I was on the accessories page on my homebridge running on my RPi4 and I clicked on the icon there a few times.  After this, now when I click to lock or unlock the front door,  on my homekit on iphone it shows unlocking... or locking... but no lock status change occurs.   I am showing this error log in my homekit.  Any advice you have would be extremely appreciated and thank you again!                                                                                                                                                                                                           Error: GET https://www.alarm.com/web/api/devices/locks/?ids%5B%5D=99950106-1202 failed: request to https://www.alarm.com/web/api/devices/locks/?ids%5B%5D=99950106-1202 failed, reason: read ECONNRESET
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:466:15
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 3)
    at async Promise.all (index 0)

**Comment by techfreakdad** [comment]
I've never been able to get the lock functionality working in HK. It shows up, but gets stuck on "updating". I'm running the latest beta version of the plugin as I was effected by the 2FA from my ISP/ Alarm.com. The logs shows the following. Any suggestions:

[telus security] (un)secureLock)(96741200-1202, 0)
[29/06/2021, 08:51:09] [telus security] Updating lock front lock (96741200-1202), state=0, prev=1
[29/06/2021, 08:51:18] [telus security] (un)secureLock)(96741200-1202, 0)
[29/06/2021, 08:51:24] [telus security] /var/lib/homebridge/ADC-SystemStates.json written

**Comment by chase9** [comment]
Looks like there are a couple of issues being conflated in this thread. Are you guys still seeing this issue with the more up-to-date version?
